# Generated by Django 6.0.5 on 2026-05-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_identifier', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=200)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
